CREATE TABLE IF NOT EXISTS authors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	year INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);
